VER2
REM Список элементов
REM IBS@ASBUFRM1
REM Версия ТЯ: 7.6.2.4
REM Версия Администратора проектов: 6.93.0.154

IDX MAIN_DOCUM IDX_Z#MAIN_DOCUM_BRANCH_ASTRDP
METH MAIN_DOCUM SEND_DOC_PACK_IN
VIEW VW_SQL_ACC_FOR_NOTIFY
